### PR TITLE
Update to version 0.1.1

### PR DESCRIPTION
**Pull request by mistergone**
**Note:** PR #10 was closed, but this PR replaces and supersedes it.

This PR fixes all current issues (#6 #7 #8 #9 #10 #11). However, I've chosen to go to version `0.1.1` instead of `1.0.0` because there is still an accessibility issue to address, in my opinion. (Watch for an issue related to this!)
## Changes
- Whitespace fixes
- Reduced nesting of .table__striped
- Various name changes
- Removed .table-cell__right-align from table
- Additional child selectors added
- .table__stack-on-small() removed from .table__entry-header-on-small
- Improved approach to table striping
- CFPB colors changed to 18F colors
- sorted_up, sorted_down changed to sorted-up, sorted-down
## Review
- @Scotchester, @jimmynotjim, @ascott1, and anyone else who's interested!
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [x] Passes all existing automated tests
- [x] New functions include new tests
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged
- [x] Visually tested in supported browsers and devices 
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
## Special Thanks

Thanks to @Scotchester and @jimmynotjim for their guidance!
## Animated GIF

Check out this @Scotchester mascot!
abe-lincoln-cheats

### CODE REVIEW

**Comment by jimmynotjim** [comment]
I think this covers everything, nice work :+1:

**Comment by KimberlyMunoz** [comment]
A clarification: What's the expected behavior for stacked on small screens variation?

image

**Comment by KimberlyMunoz** [comment]
Ah, something in the demo hasn't changed from `table__small_stacked` to `table__stack-on-small` on [this line.](https://github.com/cfpb/cf-tables/pull/12/files#diff-3e22c50371c76d64ea9738dbc46a6e57R364) Going to try to find it.

**Comment by KimberlyMunoz** [comment]
[The custom demo needs to be updated with the updated classes for stacked tables](https://github.com/cfpb/cf-tables/blob/gh-pages/demo/custom.html) (or removed since the demo already displays everything and updates auto-magickly).

**Comment by mistergone** [comment]
@KimberlyMunoz - Thanks! I'll just <strike>remove it</strike> make it an empty file. :smile:

**Comment by Scotchester** [comment]
:+1: Thanks, @mistergone!

**Pull request merged**
