### PR TITLE
Fixing BEM

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
`table-wrapper__scrolling` looked a bit off and I wanted to fix it before a 1.0 release. According to our custom BEM format, it should follow `.block-name_element-name`
## Changes
- Updated dependencies
- Fixed `table_wrapper__scrolling` to align with BEM.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1:

**Comment by Scotchester** [comment]
I'm not sure this is 100% straightforward. We still have things like `<table class="table__striped">`, which seems to imply that the `<table>` element is the block, but the wrapper is a parent of that. It doesn't seem "right" for an element to be a parent in the DOM of its parent block.

**Comment by KimberlyMunoz** [comment]
So the options are:

1.) Leave as is and close this. `table-wrapper` can be it's own thing outside the BEM notation for table.
2.) Merge this. `table_wrapper` can be a child of table that holds the table. It's weird, but still notes that the table_wrapper is related to table. 
3.) Make everything a child of `table-wrapper`. I prefer we don't do this since although correct, this is a module for tables and not table-wrappers.

I'm leaning 1. It's not as straightforward as I hoped, but so long as we agree on what kind of convention we're using, I think it's fine.

**Comment by mistergone** [comment]
Just to weigh in - I am not very opinionated about this kind of thing most of the time. Just for my insight on naming: as Jimmy suggests, I felt like `table-wrapper` was a separate "block" from `table`. Of course, there are problems from the start when you consider `table` (an element) as a block. So feel free to correct me. :grin:

**Comment by KimberlyMunoz** [comment]
I think that makes the most sense! I'll go ahead and close this PR.

**Comment by Scotchester** [comment]
:+1:

**Pull request closed without merging**
